package com.andeva.atelier.platform.iot.domain.model.dto.ai;

import java.io.Serializable;
import java.util.List;

/**
 * Master AI-generated Vehicle Mechanical Health Diagnostic Report DTO.
 * Generated by Spring AI ChatClient using structured JSON BeanOutputConverter.
 *
 * @author Joel Huamani Estefanero
 */
public record VehicleHealthReportAiDto(
        int healthScore,
        String overallCondition,
        String executiveSummary,
        List<SubsystemEvaluationDto> subsystemEvaluations,
        List<PredictiveRiskDto> predictiveRisks,
        List<RecommendedServiceActionDto> recommendedActions,
        List<DtcTelemetryCorrelationDto> dtcCorrelations
) implements Serializable {

    public VehicleHealthReportAiDto {
        overallCondition = overallCondition != null ? overallCondition : "GOOD";
        executiveSummary = executiveSummary != null ? executiveSummary : "Vehicle health analysis completed.";
        subsystemEvaluations = subsystemEvaluations != null ? List.copyOf(subsystemEvaluations) : List.of();
        predictiveRisks = predictiveRisks != null ? List.copyOf(predictiveRisks) : List.of();
        recommendedActions = recommendedActions != null ? List.copyOf(recommendedActions) : List.of();
        dtcCorrelations = dtcCorrelations != null ? List.copyOf(dtcCorrelations) : List.of();
    }
}
